# Generated by Django 3.2.7 on 2021-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
