# Generated by Django 3.2.7 on 2021-10-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_data', models.JSONField(blank=True, default={})),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.restaurant')),
            ],
        ),
    ]
