# Generated by Django 3.2.7 on 2021-10-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='gallery',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
