# Generated by Django 3.2.7 on 2021-10-21 16:40

import App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_restaurant_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='gallery',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=App.models.upload_path)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.restaurant')),
            ],
        ),
    ]
