# Generated by Django 3.2.7 on 2021-10-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_restaurant_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='review',
        ),
    ]
