# Generated by Django 3.2.7 on 2021-11-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_address_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_details',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
