# Generated by Django 3.2.7 on 2021-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_response',
            field=models.JSONField(blank=True, verbose_name=dict),
        ),
    ]
