# Generated by Django 3.2.7 on 2021-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_transactions_payment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
