# Generated by Django 3.2.7 on 2021-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20211204_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_social_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
